
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohammad
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConertFromLabel = new javax.swing.JLabel();
        ConvertFromBox = new javax.swing.JComboBox();
        ConvertFromText = new javax.swing.JTextField();
        ConertToLabel = new javax.swing.JLabel();
        ConvertToBox = new javax.swing.JComboBox();
        TheNumberLabel = new javax.swing.JLabel();
        ConvertBt = new javax.swing.JButton();
        ResultText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TheNumberLabel1 = new javax.swing.JLabel();
        ConvertBt1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Systems Converter");

        ConertFromLabel.setText("Convert From :");

        ConvertFromBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Binary System", "Octal System", "Decimal System", "Hexadecimal System" }));
        ConvertFromBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertFromBoxActionPerformed(evt);
            }
        });

        ConvertFromText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertFromTextActionPerformed(evt);
            }
        });
        ConvertFromText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ConvertFromTextKeyTyped(evt);
            }
        });

        ConertToLabel.setText("Convert To :");

        ConvertToBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Binary System", "Octal System", "Decimal System", "Hexadecimal System" }));
        ConvertToBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertToBoxActionPerformed(evt);
            }
        });

        TheNumberLabel.setText("Enter Number :");

        ConvertBt.setText("Convert");
        ConvertBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertBtActionPerformed(evt);
            }
        });

        ResultText.setEditable(false);

        TheNumberLabel1.setText("The Result :");

        ConvertBt1.setText("Clear");
        ConvertBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertBt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TheNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(ResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TheNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(ConertToLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ConertFromLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ConvertToBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 177, Short.MAX_VALUE)
                                    .addComponent(ConvertFromBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(ConvertBt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ConvertFromText, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ConvertBt1))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConertFromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConvertFromBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConertToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConvertToBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertFromText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TheNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConvertBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(ConvertBt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TheNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertBtActionPerformed
        if(ConvertFromBox.getSelectedIndex() != 0){
            if(ConvertToBox.getSelectedIndex() != 0){
                if(!(ConvertFromText.getText().equals(""))){
                    CkeckBeforeConvert CBC = new CkeckBeforeConvert(ConvertFromText.getText().trim(),ConvertFromBox.getSelectedIndex());
                    if(CBC.CheckInput()){
                        ToDecimal toDecimal = new ToDecimal(ConvertFromText.getText().trim(),ConvertFromBox.getSelectedIndex());
                        int decimalNum = toDecimal.getDecimal();
                        FromDecimal fromDecimal = new FromDecimal(decimalNum,ConvertToBox.getSelectedIndex());
                        ResultText.setText(fromDecimal.getSysType());
                    }else JOptionPane.showMessageDialog(null, "The input number dose not match the selected system","Error Message" , 
                                           JOptionPane.ERROR_MESSAGE);
                    
                }
                else JOptionPane.showMessageDialog(null, "Enter a number to be convertd","Error Message" , 
                                           JOptionPane.ERROR_MESSAGE);
            }
            else JOptionPane.showMessageDialog(null, "Select asystem to convert to","Error Message" , 
                                           JOptionPane.ERROR_MESSAGE);
        }else JOptionPane.showMessageDialog(null, "Select asystem to convert from","Error Message" , 
                                           JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ConvertBtActionPerformed

    private void ConvertFromTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertFromTextActionPerformed
        
             
    }//GEN-LAST:event_ConvertFromTextActionPerformed

    private void ConvertFromTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConvertFromTextKeyTyped
//        switch (ConvertFromBox.getSelectedIndex()){
//            case 0 :
//                JOptionPane.showMessageDialog(null, "Select a system to convert from","Error Message" , 
//                                           JOptionPane.ERROR_MESSAGE);
//                evt.consume();
//                break;
//            case 1 :
//                if (evt.getKeyChar() !='0' && evt.getKeyChar() !='1' && evt.getKeyChar() !='\b'){
//                evt.consume();
//                JOptionPane.showMessageDialog(null, "Type 0 or 1 only","Error Message" , 
//                                           JOptionPane.ERROR_MESSAGE);
//                }
//                break;
//            case 2 :
//                if (evt.getKeyChar() >='0' && evt.getKeyChar() <='7' ){
//                    
//                }
//                else {
//                    evt.consume();
//                    JOptionPane.showMessageDialog(null, "Type a number from 0 to 7 only","Error Message" , 
//                                           JOptionPane.ERROR_MESSAGE);
//                }
//                break;
//            case 3 :
//                if (evt.getKeyChar() >='0' && evt.getKeyChar() <='9'){}
//                else {
//                    evt.consume();
//                    JOptionPane.showMessageDialog(null, "Type a number only","Error Message" , 
//                                           JOptionPane.ERROR_MESSAGE);
//                }
//                break;
//            case 4 :
//                if (evt.getKeyChar() >='0' && evt.getKeyChar() <='9' ){}
//                else if (evt.getKeyChar() >='A' && evt.getKeyChar() <='F' ){}
//                else{
//                    evt.consume();
//                    JOptionPane.showMessageDialog(null, "Type a number only","Error Message" , 
//                                           JOptionPane.ERROR_MESSAGE);
//                }
//                break;
//        }
    }//GEN-LAST:event_ConvertFromTextKeyTyped

    private void ConvertFromBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertFromBoxActionPerformed
        ConvertFromText.setText("");
        ResultText.setText("");
    }//GEN-LAST:event_ConvertFromBoxActionPerformed

    private void ConvertToBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertToBoxActionPerformed
       ResultText.setText("");
    }//GEN-LAST:event_ConvertToBoxActionPerformed
        
    private void ConvertBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertBt1ActionPerformed
        ConvertFromText.setText("");
    }//GEN-LAST:event_ConvertBt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConertFromLabel;
    private javax.swing.JLabel ConertToLabel;
    private javax.swing.JButton ConvertBt;
    private javax.swing.JButton ConvertBt1;
    private javax.swing.JComboBox ConvertFromBox;
    private javax.swing.JTextField ConvertFromText;
    private javax.swing.JComboBox ConvertToBox;
    private javax.swing.JTextField ResultText;
    private javax.swing.JLabel TheNumberLabel;
    private javax.swing.JLabel TheNumberLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
